
#!/bin/bash

clear
echo 
echo"""
:,;;~~___!!_;~,`    .`-,;~___!!!!_;,:';_!!!!!!!_;~'-.--`---``.-',':,,,-`-.``----:;~_______~;;~_____!!!!!!/=1ivr!_____!!!!__;~;;~~~~;;;;;;~____________!!!!!!!!___!!!____~;~;~~~;;;~~~~__!+ifIb0#gggggggggggggggggggggggggggggggggggggmm#mm#m0000qqEIIulzi1i+++=/
',,;;;___!!__;:`     ..,,;____!!!~:::',_!!!!!!!_;''.-`---`.`-.-'::'',.----.`-``-,';;_______~~;;_______!!!+=vvv/!!__!!!!!!__;;':~;;____;~;;~~_____;;___!!!!!!_____!!!!___~;~;~~~;;~;~__!*icFh0mgggggggggggggggggggggggggggggggggggg#m##m##0000bhhIInjc|xi*\\r/+\r
,'~~~~___!!!_~'.      -`'~____!!_;:,:,:_!!!!!!_;;::-.---.``--.`-`-.-.`--.`-. `...:'~;;;____;~;;~_______!!\riv1\!!__!!!!!__;;::;~;__!!__;~~~;____~~~~___!!!!!_____!!!!___~;;;~;;~~~__!!*vfed0#ggggggggggggggggggggggggggggggg###g#m#m#mm000qbEkIjulziv\/+r+r=+\=\
~~;~~~____!!_~:.-     `-:;_____!~''':'_!*!!!!_;~',-`..`---`..`-`-..``````-.   ``-,:;;~;;~;~;~;~;_______!!=*ivi*!____!!!__;~,:',;__!r+!__;~~~;;~~;~;~____!!!____________~;;;;~~;;;_!!+rzued0#gggggggggggggggggggggggggggggggmmm##mmm#000bdpwFfjzvx1x+*r=r==+=*ri1
;~;;;;~__!!!_~''-`    --:;_!!!!_~~,:,;!!!!!__;;,:.`-`-``-.`..-.-..``.``--    `.`.,,:;;;;~;~;~~;;______!!!*\1v=!!_____!___;;~;~;~_!+xv=!_;;~;;;;;~~~~____!!_____________~;~~;~~__!!\1zuypd#gggggggggggggggggggggggggggggggg#mm#m###000bEyFTt||ivir=r=r/rr*=vx||uf
~~;;;;;__!!!_;~:`-    -.,~_!!!!_;';;;_!!!!__;;'':'`-.-`..`-`-`--.-.`-.`-`.`.`````.,:,;;~;;;~~;~;_______!!+/11*=!____________;;__!*\i1+!_;;~;;;~~~;~;~______________;__~;~~;~~__!*xcnhd00mgggggggggggggggggggggggggggggggg#m##mm000bhEoTs|1v1*/+r\++rr\/+\iilzjTn
;~~~~;____!!__;~,`-.`-``:;_!!!!_~,;~~_!!!!__~~:''',''`....--```..-.--.`--.-..-..`.:':;;;~~;~;;~~_____!__!=*xi\=!__~_____________!!+\*!__;;;;____;;~~~~___________;;~;~;~~~;__!=vlFpd0#ggggggggggggggggggggggggggggggggmmm###00bqEEoou|v1v*+=\/*/\r\!!!!!!\+\ixcc
;;;~~;;__!!!!_;;:`.`-`..'~_!!!!~;;~;;_!!___;;;~',:,:'````--.``-`.`-.`.-`-``..--`-',:,,~;;;~~~~;~~;_____!!\+vix/!__;;~~~;~____~___!!!!__;~;;_____________!!!_____;;;;;;~;~__!!=zuh0#gggggggggggggggggggggggggggggggmm#####000qwFFIjszxx1*r\\*\==vxi1\+/!!\/r+//*1
;~~~~;~__!!!!__~::',,.`,';_!!!!;;~;;;~;;_~;~~;~~,:',:-`.---.`.-.-.`.--..--.-..-.```',,;~~~~;~;~~~;_____!!*=1xr!!___;;~~;;~;;~;~_______~~;~~__!!!!___!!!!!!!_____~~;~;~~;__!=xlFw0#gggggggggggggggggggggggggggggggmm##0000qbEkucsccvi**/*\==ixvlsnufzzxv1+r*rr**+
;~~;;;___!!!!__;;::'':''~;_!!!!_;~~~;;;;;;~~~;':',::.`-`-..```-..-``.-.`.-.`-.`.``.'::~~~;~;~;~;;;____!!!=\xx!!!___!___;;;;;;________;;~',,;___!____!!!!!!!____;;;;~;___!!rcuE0mggggggggggggggggggggggggggggggggg##000bdhIyTssvxirr\=/\xxicjuekeEpaoITjtzxxvii1x
;~~;~____!!!!!_~;::':',,;;__!!___;;;,,,:~;;~;~'''::'-....``..-.`...-.`.-`.`-..--.`-:':;;;;~~;;;;;~___!!!!/+xv!!!!!!!!!__;;~;_____;_~~~~~,:',~;;;~;;___!!!_____________!!*i|ob0mggggggggggggggggggggggggggggggggg#m000qhkojlx11ir/**ii1tsfkyIkeIkIIeokunntivixlcl
;;~_______!!!!_;~''',',::;;____~;~~;::':~;;~~;,',:'.``-.``.`.-``-.--``..``.`.-`-..-:',~;~~;;~~~;;;___!!!!+/ii=!!!!!r!!!_~;~~_____~~;;~;''',',';;;~~;~~_______________!\r|Tp0#gggggggggggggggggggggggggggggggggggm#00qaefll1x\*/i11ltfkowadwahofttvx1i1\\!!!!\*+i
~~;~______!!!!_;~,-.'':'::;~;;~;;;~:'':'~;;;~;''',,:``-....-.`.`- `--``.-`-.`````-:,''~;~;;~~~~~;;~__!!!!+\x1i1\=r\!!!__~~~~____~;;;;;~::'::;;;__~;;~;_________~___!!+vlyp0#ggggggggggggggggggggggggm###mgggggg###00qeTss1xivitzTfkphdd000qpkuzx\++=*+!!___!!!*\
~;~~~;____!!!!__~,,,'',:'',~~~'~:':''','~~;~~;,',:',,.`--.`-...-- -.``-`.-.``.-`.-,:'~;~~;~;;~~~;;~;__!!!\riixvv\!!!___~;~~~;;;~;~;_;~;;____!!!!!!!_________~;~__!!\ijeh0mgggggggggggggggggggggggg##mmm###ggggg###00EFTczszlsnfeywpqbq0qdqEIjl1/+/*/*\!!!__!!!r+
;;~~~;~___!!!!!_;;':'',:,:;;;::,''',':':~;;'''',,''',`-..-`.--`.- .`---`-``.-`-..'''';~~~_;_;~;;~~;;__!!!=*1vxv=!__~~~~~;;~;;~;~;____!!!!!*/\/v1i/=!!!!!!___~~__!+ickEqmggggggggggggggggggggggggmm0000000#mgggm##m0qwe|ixvvi1t|zfTeeIojuTnunjTtsltzzivx=\r=vivxx
;;;;~~~__!!!!!!!__~~~::''';;~,::,'''':,,~~,:,,,','''``-.-`.-`-..- `-`-..-``-.--`-,::,~;;;____;~;~;~~___!!r\vx==!_;~;~~~~~~~;~;;~__!!/+viitzcczcct1x*=!!!!_____!=1lnpq0ggggggggggggggggggggg#m##000bdqpbd00mgggm#m00bojtvs1vivvi|czczlii11czlcnTjnTztsczt1vitc|vv
~~~;;;~__!!!!!!!!!_~~~~~~~~;::,:''':::''':,,'',''':..--...-,```-.`...`.`,':.-`:-,'::,:~;~______~;~~;~__!!r\1x+!!~;:,~;;~~~;~;;;;~_!!*xvt|jnnnj|l|si1//\!!!!!!+1tjwd0#gggggggggggggggggggggm#000dqEhoFewad0mmmm#000dhyjz1cvi1vv11i1vvx**r\11ztsujz|ztsltviivxiix1
;~;;;;~;_!!!!!!r!!__;;~~~~~~,',::,,:::,,'',':':,:''`--.-'-.'`-.--`-`.`-`:,',,:'''''':'~~~_______;;;~;~__!/rx1=!__~:':',;~;;~~~____!!rx1||fujjTt|ssxx//!!!!!/rifIp00mgggggggggggggggggggg###0bqqEIIfjzsTIEb0#m0000bdEInsxrr/+r!!!!!!!\=!!==1tssstlczscvi1vv+ri1vv
;;~~;;~~__!!!!+!!!__;;~~~~~~:,':.--``':''``-`-`'.-.--.`,,'',,`.`.--``..`:,',,,',::',,',;;_________~;~~__!!+\r\!__;;;',,'';;~______!!!r=xix|l1vxx11=\+!!!!/r1l|khEd00mmm##m0000gggggggg#m00dEEeFuz1xirvcjkp00000qbEwFn||v1xv/=*+/=+/+r/+r+ivztclxv1xx11++r\*/xirr
;;;;;~~__!!!!!*+=!!__~~;;;;;,''.-.---,',:`--:'',---`-`-:',',:.`..--`-`..':''::,,,:,,:::;~_________;;~~;_!!!*+!!__;;~~~;~~;~;________!!!!+//+*r!!!!\++/r\+=vssjkphhwapEdqakykeyw0mggg#00bdhekncl1=+r!!!x|uwdqqddqdahkntxvxx1r=//*++\\r\rr+++1x1vv++\=r=/+\!__!+xx
~________!\*==xx*\+++!!___;~':`-..,::,,',':':':'-'``--'',::':-.`-.--.-..:':',,':':'::',~~__________~~~~___!!!!!!_____________!!!!!!!!!!!!!!!!!!!!!!/*\=ivxttunufkoyufjctciix11zFEd00dqaeFuzvx\+!!!!!!!rlfabqdbqwhEeojsixi1xxvi1vvx1x++=!!+\/*r+r=\/**=*!_;~~;_!v
!!!!!!!!!r/v1vxl1xvx1c1i=!__;:'::::,~:,'',';:,'::::,,,:,:',,:,::`-..`-`.,':':;~;;,',,:,~;~__________;~~~___!!!!!!!!!!!!!!!!!!!+++r+r=++**r//\+!!!\==*i1il|ujfuTffTctl1vi=*!!!!\lfwdbhEefsvr+**!!r!r!__!=ndbbEaEEwFon|zc|tsufstlszs|tiiv*ix=+/v1\rr\\+*/_;~~;~~_r
=/r=\rr+/iixtcTfuuIekokzi/!_;',,;;~;~;;;~~~_~;~;'''',',,':,:,',,:-`--..,::::;~~~~~;;,:~;~~__!!!!!____~;~;__!!=*\*++*+*\\*+//r1ii1x1iv1i1ix1111\=vv11vsl|nnuujfjnnz|i11=*!!!!!!*sjapwkutci+r=/*+1vtx!!/*xvb0dhEEeoyjjc1illcctcsltszscvvxvvxviivxxrr!!!!!_~;;~;;!\
1iststxvv|lszjoFahqqqbhIzi+_~;;~_!________!!!__;;~;'''':,':~;',,,,-.--,,''~;;~;__;~~~;;~~___!!!!!!___;~;;__!*xctccss|slz|zz|ttzzslttuTnTunjTffltzzzcjTjTjujTufTuTtsi*=\!/++\*/1slypeyTtzvxiilllfjojr1v|iipdpaFIIoejs1i11i1xi1xvctctTz|tvvxivlcxv/=!!__!!_____!/+
xc|jffust|zzcjyhqb0dqwIt+!!_;;__!r+!!!!!!r*\!!!_;;~~~:,:;~~;~~:,:'..-.::,,'~~;______~;;~___!!!!!!!!____;;~~_!vtfIyfjfnnn|zsclllulslsztsuTffTnfoTnukwawoIeFekewFFuli/*+/=iv1x=r1lfyhIoT\!_____!!/jhpTvxxiupaIFeyFTj||v*i11xvctcnTjkeeITlvxv1xcczi+!!___!!!!=r/*/!
zzTnoe1!_!rctjIpd00bwIc\!__~~__!/111lvr=r*r/r!!___;;~::,;~~~;~,,:'.--`':':~;;________;;___!!!!!!!!!!__~;;~~__rnkFIyeeFIyeFoIeokonjkkEwbbdEwwab0m#gmmggggggggggdefsvvixvllsivvvilTFFoT/_;':',,;;_!shhhejkyeeoeffuujszvixi||zTuoyphqbbqInz1111ssxv+!!___!!!*v111\!
eEaahi__;;~\ljFEaqhIflr!~~~;__!!/vttslvvixrr\!!____~~;~~;~;~;~:'',:'.:',:,;~;_______;~~~__!!!!!!!!!!__~~~~;__!zTokeokFyFFoyq#mggggggggbhqggg#bbawd00#mmmmggggbyTucccczcTjTtlixxclIITz!;:,':','',;_*fawFnzslnTfjujTssi1|cjkohawdb0###0pnzix+xtllxi*!!*=1v|TeFnsx*
wab0dr!___~!tuIeaakt1*!;;~;___!!/ils|tiv11+*/!!!!!__;;~;~~~;;~',:,:,-,,,:,~~____!___~~;~__!!!!!!!!!!__~~;~;__rxzlufnjnfu|tltlTuo0gggggg@ggg@gggggg#q00000mggqokjjuljTTfTnTzxxxv1cnujx!;',,''',,';_!=jFutx|zlujujscltsljyFEabqd00m#mm0hTc1tzTkFnfjlzljueFpbqbolxi
qq000j!__~_+zuyyonl=!__~~~____!!=vtszsxxvr+*=!!!!!_____;~;;;;~~,:':,`,,',~;~____!___;;~___!+=*rr=*rr!__~;___!\riztlccs|jwIb0yuc0gggg0m0mgg@@@gg@@@@@@gggg000qpoIfTTjnuTjT|t|llz||Tnltr_~~;;':~:;;_!rTk|vvvzc|c|cs|ssslkwdb000000#mm#0qhyFyehEaawaEaqb00#gggaiv!!
qdbqb0Ez1vszcfujTtv!_~;~;_____!!*1xscxxxxxr++r!!!!______~;~;;~~':':'':,,:;~;___!!___;;;__!!+\*=+//r+\!!___!!\/=1*w0gg#h0g#fkgmq0#q0#g@ggggggg@@@g@@@@@g@@@@ggwFujzzczltctzz|ccjssuzstc/!__~;~~___=swpyui11it|ctlczcl|fkEd0000000##g#0bbapdddq00000###ggggg#jlv!_
wawbbqbwofslljuTcs\_~;~;______!!+\11i1/\*\ii*\*+!!!____;;;;;~;~::','':,';;;;____!!___;~;_!!=r+\***r*=r/!!!+=r*=1Tjw0ytodadgqg#ao0ggggg#0m0Eqmg0wFobgg#gggg@@@@oTscvivvizcltctzTuTuz|iv11sxivtcTohEb0bETsxivslzl|zlv1zjed00000000mmg##0000000000000m##mggmezr+=!_
ufkkapapIjtt|lcz1*!_;;;______!!rvxvi*+r!!/+=r/*/!!!____;~~;;~~~',::'''',;~;;____!!__~;;;;_!=*r/r=/++*\//*=iicokjlag@@ggggg@gg@@@@@@@@@@@a1hg#cshwt*!zhgg#0g0ggg0fv=r=xvxxzc||lulju|cvi11i1vvi|feq0m#0qyzi1ix1zlxx1iitfFq000ddbq00mm#m00###00qbapwpddd00p!!!!__!!
1xxi1lc1vvx1xvv1=!_;~__!!!!!!!*i1v/\!!!!!!!!!!__!_!___~~~;~~;;:'::':'',',;~~;~__!!__;':':;_!\+=r\rr/=\r*+1kuyw#b0gg#qbIzrjeifpkyFEq0dlduvlx|0ggggggg@@@@ggggga#gggg01+111txiil||ufnlv1xi1vxxz|Twq0##0hjc/+vvi1v1xv1xtlIhahEFFkeEq00dqbqd0bqhkTfnnujukhpv_!!___//
______!!!!!!+/r!!__~;__!!/!!+*ils1x\!___________;;_;;~~;~,:',:''''::,,:'~~~;~______;~:'::~;!*+\+r=!!!*i|jzcwk1xrub#mggg0yTuuegggggagg0igf#ggggg@@gg@gg@@@@@ggg@gggg0gggktli1iicznTf|1ii1ztc|zTfhd0#mqaTv+=1vivvxi1ixilnoIeTciisTyawkeyIpwwEFnlvvvvxtuykj!___~!=!
':''::::~;~_____;~'';;_!!!!++ilzll1+!!!__!__;;;~~,;;;~;;,':::',',,,:',':~~~~;;;____;;:,::;_!*rr=!!!!s0q0fmgbs#000m000ggp!tTd0g0Eqg@fn00ggggggg@@gg@@@@@@@@@@@@@@@gggg*g@gul\\vvsTnusx1vvctlzzukd00#mdkz1rr1ii1i1xvxv1stuftv\!!\rzuTutcnfIfufcv*/*=1t|njjsr!_!+!!
',`...`,,''~;~;',::,,~;__!!+=iszll1r!!!!!!!__~~;'':::,~,:,',,',::,'',::;;;~;;~______~~~;;~_!=**\xngm#bFb0o|skgg00dpdnzIe00gggggg00mggg#bp0d###g00gg@gg@@@@@@@@@@@@@g@@@o@@#sxcsffjcl1v1ttltnnkhd0#mmqFt\+**vxiv1xix1vistsx\!__!\1cusclzffTssi11iix111t|||x1=!!!!
:,`--..-'':::',:`-..`',~;_!!\1z|tx1r!!!!r/!!__;~',,:,:~:''',':,,,,':''':;;~;______________!!/+rd0qatv*!b#T0q00wbxijThqdd#mgggqhgggwFg@@@ggg@@@@@@@@@@@@@@@@@@@@@@@@@g@@@@@@gnllfekfs|lx|||ljFIp00#m#bos=//r+ivxxvxi+1iz|zvr_;~_r1sfls|snfls|ccltsl|v/1*1r\\!!!!!
,:..---:',''''..``--.-'~;_!!=iixiv+!!!!!+!!!__;;;;':':,::''::...``,',:,,~~~;____!!!!!!_!!!rr+ka\l|*!!_!wggmbeok0bpbETFllpd0Fg#gggg@@g@g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g#@@g0nIukkFjslztslzfoFhd0mm#qk|+\rr\v11vv=/\1il|c!;~~;~!lnjuffnnuunTnffcsz11\r=!;;;~_!!!
':,-`.-.''',::--.-``-.'~~__!!!!!!______!!!!!____~;''':,':,:-.`-..`.',':;~~~;_____!!!___!!!!+**+!r*rwbd#dEmbmbivqggg@@@@@@g0#@@g@gaFIpaqqwamgg@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@@gjooohyjTttz|tctfTkad0m0pTvr\*\+r//rr+/=1||jt!__;__!tnjz|cujyyfnfjTjlz1ix1\______!!!
'',:``..::':''`-``.-.`:'~;~____;~;;;;;~_________;;~''':,--.``----`.`:,,:;;~;_____!!________Iva#ws!ybengguo1|gggg@@ggg@@@gbg@q!b@@m0dgggg@@@@@@ggg@@@@@@@@@@@@@@@@@@@@@@@@g@0@@yeIhknTl|xtzvczTypbb00wTir!\//r/\\r=r*vxzst\_____\nutl|jFjneIjsctsslzxls1!_____!=!
,:,'--.:''',,'..``.-``:,'~~;~~;':,,::~~;___;;_;;~,,':'',:'-`-`-.``'-',''~;;;______________\g#0oxh0g0g0qTdg#ggggg@@@@@ggegqcggg#mggg@@@ggggggggmqqmmmgggg@@@@@@@@@@@@@@@@@@gpg@gjTnhots|ixxx|cukwpd0qks+!!*=*+r==r\=/11xctzr!!+xcuczicfufTfcvii\vcscljjnz=!!!*=*!
,'''`..':'::'..'``.:.`,,:,;;~;~;;~,:~~~;_~;_~;~;:'''`':::,:'''`,'',,':',;;;;____________*egmbzgF#mq00iggEgggg@gggmgg@##j#g00g@@@@@@@@@@@#0g@@@@g@@@@@@@@@@@@@@@@@@@@@@@@@@@00@@ycn0hzc|ilzlsTfehb00qFl+!!+*/r*\r=*/rxzls1i\\ivtlsvl|sfFFelx*+*rrtlTToFkkEoflxr!!
,::`--`''::':.-``:',,:'',,~;;~~~~;;~;_____;;~~;~,:',',;;;;'':::''''',,':~~;;____________/p1rIIwg00gmtdbgggnEdqggg#@ggvm#0g@@g@@@@@@@ggg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g#g@0sugbczcxtz|lfjFEqqqanc\!!\rrr+\=\\r/1|vvi\r!**1xx1slfkhhuzv\!!\xcTywEapkofcx/!!!
:''-``-,',::,:,,':'':'':,';~~_________!!___~;~;~;',:;~~~;;~~;~;'::,,,::,:~;;~________!!vEft0wd#q##0w#gm000pgggg#g@geu0gg@@gg@@@@@g0g@ggggg@@gg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggTkgq|zsxszcztukkhawelv+!!rr=+++r=rr1|luci/!!!\+r/iizueEhu1*!!!\sjoEqhpawInsr!___
,':`..--:::''':':,:,:':,,';;__!!!!!!!!!!!!_______~;;_~_______~;;;~;;;~~~~;;;______!!!!!*\gqbbgmggbaTmagpg@@@g@g@ggrFgggg0@g@@@@g0qI0gggg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@ggc0ghjTczllclujkIEpoTz=!!!+++=*r=/=\1cnIut1r!!*\/\vvlneEwj|+/!*iteyphwhpaenir!___
:,'..`:':,':,,',''',''':'~~;__!!!!!!**+*r*=*/r=!!______________;;~~;;;;;~;;;______!!!!+o00eagmggkggggqg@@@gg@ggggxgg0gg@@@@@@gba#g@gg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gggggofjTTT|zcnnuoyoefi*!!!////**/=*rilkoeFczx\xxxixcTeahpeji1\vzz1vxtnkehITv=!___
:,,--`'',,',',,,'':,:':';;;_!!/1vv\/=+ltss|sxx1x==!!!!!!!!______;;;~~;;;~~;;___!!!!!!=abdkg#dggggmg0g@@gggg#ggg##gmgmgg@@@gp|#ggg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gggg#nIIeoIfjTTjFkhhFnv+!!!r\+\\r*\=r1copbajl||ct|scTaq000qkuczz1!!!!!xTpphysv!!__
,,:.``'::'::::,',:,:''':~;;_!!rxxix*+ic|sfnnctl1x*!!!!!!!!______;~~~''':,~;~___!!!!!!fb0mg#ggg@#gg0@ggggg@gaggq@gggp@@@@gw1#ggg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggg#gmTToeokoufunyphwaFc/!!!+\==/*\=+=vuFEdwouTffujuyFa0#gm0qaeTn=!!!!!\uw0qbIs/!__
'',-..,,:,,,','':'''':',;~__!+\r\vxi\vzsTTuusTlv=+!!!!!!!!_____;;~',.-.`,::~;____!!!\d00ggggg@#gqgggggg@gg@0g#gw#gggggmnsqgg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggg#0g0cTTeyFenfujIppqhfvr!!!!\+/\\r=+\itowqhaFFkIIohwhbmgggg0qwaFv/!!!!iId#m0It+!__
,':'''-:,,::,,':';,'':':~~_!=\\+++/*\v|cccfjccc/\!!!!!!______~~~;:,---`-..'',;;~___!eq#ggg@g@0@g#ggggggdgFgT#g0mgggg@gwggggg@ggg@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gggggg0goiznujfjsttsnyykej1/!!!rr==//\/\vvsIpqdEEpwEpwwpd0mgggg#0dpFli=rrfad0gg0aj\!__
,,,:`--:,''''':;;;;;:,:';~_!/ix\r/r+vsslzcTut|v/!!!!!_____;_~;~,,'-`    ``-.,,';~;~_0gggg@@@ggmggggmm0gggggggg0wg@ggk#gg@@ggg@@@@@@@@@@@@@@@@@@@@@@@@@@g@@@@@@@@@@@@@@@@@ggggggggg0u+lstcx1+\1vcnjl1\!!!!++r=\//\*rxckhphEEhEabdqbbq0##mm#mqFFejjuhqbd0gg0es\!__
:,,':,.'',',,,;;~~~~::'';_!*viixr=r/iss|nTunttx!!_____;~~;;;~~~,:.-`     ....`',:;;;0gd@gg@ggggg00ggq0j@gg#gapg0Tofwg@ggg@@gggggg@@@@@@@@@@@@@@@@@@@gg@@@@@@@@gggggggggggggggggggggmEl1ix*==!\/=i1=r!!_!!\+\/\/*\=/=iljnyFyIyooyaaaohddbqqdhnuufuuadd00gmdFt+!__
:,:,:',''',:,~~~~;~;,';;;_!*is|1r+!!+r1izfnTtv*!__;__~~;;~;;~;''`-`-     .``.:,,:,;~nmggg@gggggggguFymggm#aqTzmggngggggggggg@ggggggggggggg@@@@@@@@gg@@@@ggggggmm000#ggggggggggggggggghc1rr\!!!!!rr/!!__!=+=+\\=\!!!!+\ivi1iix|slzst|c|nTjIIeti1vl|nhEd000ETl\!__
'',:`-`-,::,,~;;;~;;:';;~~!!/1x1*!!__!!+vslcsv+__;~__~~__~~;;,:.-.-       .``.:'',~;*0ggggggggggmbm#gd0qubuFggg0i#gggg@gggggggggmmggggggggg@@@@@gg@@@@@@ggg0#0dddahqd0gggggggggggggg@g0n1i/!!!!!*ixr!!!!!/\=/*\r!!!!!!!!!!!!!!r+**+r*=*\=ixii===/xvsnfoFeTlr!!__
':,,:---,:::;~;~~;;~',,:;~_!!*\//!!!!!!!!*/1+=!_~~;~__~____;;:,`.`-       .-`,':'',;*0gmojggggghgg@dEwyv0ggmg0wv@ggg00g#qEyIebmggggggggggggggg@m@@@@@@gggg00bbhwEIIIphwb00mgggggggg@ggg0euxr*ivizTu|/!!!!\/r/*r/=!!!!!!!!!!____!!!!!!!!!!!!!!!!!!!!/=+\r\*=!____
':':,--`',::;,;;;;;;:':,~~~_!!!+/\vx/!_____!!_~~;;~~_______~:'..`..`     ```.,::;;::!gomggggggm0ggdtkg0#g#bggdyggggggquh0ggggggggggg#gggggggggggggggggg#0bqpEEakkunfjyoehEd0#mggg@@g@@gbaeus11tjhdoT1/!!!*\*=+*\*=\=*x1+\=!!!!!!!!!*!!!!_________!!!!_____!_____
,::::','',,'':;~;;~;::,'~~~;__!rxzTku1!_~~~;~;,,':;~______;;,:----..   .-.--',,~',,,;g0ggggggg0#gidggm#gqmgqgk#gg0Id#g0ggmg##00gggggg#ggggggggggggggggm0qpwIknuTuTTfnnTjueIwdb0g@@g@@@g0qwyjlnhd0#det+!!!/*=+rr**+i1tunuTlcziviivv11\==!!_______________________
,:::-``::',''';;~;;~;;::,~;;~_!/1kpdwnr_:`--`--..,;__!!___~~',,--`-``.-.-`--::';~',,:Eq0ggggggg0md@g000##gg#dgddmggmgpyyw00g#mm#000m#mm#mggggggggggggm0dhFynnnfunTzc|zss|feFawwm@@@@g@gmdphInFh0#m0p|*!!!!!+*++/*itjEdbbbqwaEkyeokouuttx=++!!!!!!!!_____________
:':'''-'::'';'~~~~~;;;,';;:;~__!iTpbhn/_'`..`.-`-'~_!!!!_;;;,,,,'`.`---.`--`::'~;,'':!b#ggggggd0bgksggg#ggg#kq0000#0m0##mm0000000000000000g##mm0m0#00ddEpeyuffTjjj|||lssctTfekaqg@@@ggg00qEefkkh00bec=!!!!!=!r**+xlkd0mm00000bbbqdqdawhoujt|z11v\r/!!!!!!!!_____
'::,:'','~~;;;~;~~;~~~;~;;,;~__!xfEbhf\_'`.`..-`.';_!!!__;~::,:''-`--.-`-```.,',~,',;_0#g@gggbEg@qgmggg@g@gmgm0000000000mqb0q00qbb0000000m0000000000qahwynuntcctcltzlTjnlcffjyyyg@@@@@g0qhpyffnkeEycvr!!!!!!!==/+xcuhqddqqqqqqb00dddbqqEpFeIujuj|ttc1xxv*!!_____
:'',,':,,;~;;;;;~;~;;~;;~;~~__!=zTFEFi!;'.-..`-.-,~_!___~;,,,,,:'`.---....`..-:,,,,':,pgg@@ggdgtl0gggg@g@@@ggm00000bb000Ed0qbdddqbqqqbdb0qdqdbhbddbdhaeoFnf|stssztsc|||ts|nujnTob@@@@@#waaynccx1xiv/!!!!!!!!!/=\r/vcTkIfouyFIoyyEpEpEapwwyykkyFIjfTntszi/!!_____
:':':,:,;~;;~~;;~~~~~~;____!!!!1cjFyc\_;,`.-.-`..::;___;~''::'',:`-`..'``-..-..`.`::',hgggg@eg#0gggggg@g@@ggm000bdbdqdqpqdwwwhpEawwhhahd0qdqbddbappwwhyInuTl|tlzlctltzcs|ztzffuTa@@@@@qhFkkTcx*!!!!!__!!!!!!!!/rrr/\+ixxiv1vszt|cccuffufTujujTnfnfuuucz1=!______
',:.-:,'~;;;~~~;~_____!\==/**rrvnouTv!;',`--`````,:~;_~~;,,:,,':,``.`''',..`--`---.`'-oggggg#ggbgggg@@g@@ggg0bpdwEhwahEEahahppEaEhkapha0hEdbqqqawbbwEeoTzlz1x1iv1xic||csc|z|uffuog@@@gwEIII|s\!!______!!!!!!!!==!!!!!!!!/+*/==*r\*//i1ivxi1xxzzct|zz|li\!!______
,:,.',::;;~;;;~;__!!r++x|zczzixcjT|1\_;:,.```..`-',~;~;~;:',,',````.-,':-`.-.-`-.---.-t00gggg#ggggg@@g@@@gg#dqwwoFyooIIyIoIooeFFoekekoEpypawhaphpaekIfTll|clxzvi1v1clsc|lz||lTcuTg@@@gwyFIuc1+!___~;;_!!!!!!!!\+!!!!!!!!!!!!!!!!!!r*+*r/rvxxvvvvxxx1iir\!!______
'':-:,:~;__~;~;__!*vvvslfuuscxxx1vv!_~:''``---.-`',,'~~~::''`...---..:,:'`.`.-.`.-````!y#mgggmgggg@gg@@@@gg0poyfnnfuuujujfnunjjjTnfknu0eoFeFEpwEkyFIjuucttttc|iivxv|s||csccztcnuug@@@#ofnunci\!___;~;_!!!!!!!!/=!!_______!_!!!!!!!!!!!!=*/+/\r=vxxv1x+/=!!______
,',:''~__!!!!!!!+\i|lszss|||v\+!!!_;~'-.`-.....-...-'',~,''-.``--``..`'``.-.`.-`-.`-`.~oqqggg0ggggggg@@@gg#qncjsstccxtclc|tz|nnujfTnnudufffyeoyokknunczsslxx1xvxvivi11|zt|ltczTuug@@gj1zctt1v/*!____;~_!!!!!!!!/!____________________!!!!!!!!*r=/+*+==\!!!______
,-..,~_!!=+++/r1v1cnnTzcscct1+!;;~,:`..--`---.--.-.-.:',:,-`-..-.--.``::```-`-`.`-``.`'tb0#gggmgggggggggg0bsz|vixixvvi1vs|sctccunsclsyu|ltzc|ffTusl|zcs1xv1/i***1vi1viitzscslnnfug@@a++/\\r*r*r/!!____!!!!!!!!+!!____;____________________!!!!!!!!r\/\!!!!______
-.``:~_!\=1|ct|t||Tuunczlunt+!_;,`..`-`--.```.-`-..-..:::-`---`-`-.-....```.``.`.`---``+ub0#ggggggggggggpjcixi/rr===\=/1|xi|ssuuus11vuis|sc|zs|c|t|zlzi1xvv/++=\+\//i/xx1||cTjfftg@m!_____!!!\+r***r!!=!!!!!!!+/!___;___!!___!_!!!!!!!!!!!!!!!!!!!!\!!!!!_______
`..`,~_!!\sjuTjIFnfkFFTttzxvr_~'`..`-..`.``````.-`...`.`---``-.-..`..-`.-``.`--...-`.--~ub#mmm0gg#ggggduliv1*/rr/r+\=vivfh00m0ajFllc1nsvx|slc|tctl|z|svii1xi///xx=+rr*xvxvz|unnusg@s~~;';~~____!\x1/\*r+!!!!!+rr!!!___!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!________
.-`.,,~__!=sjuIFkyeIITsii=+!__;:.`.``....`.-...`-----....--..```.`-`-..---...``--.```,::|oqqm00#0ggg0w|//!!/!!!!!!!/*1thh#0EEEd0hwbahITjulsztln|z|sxx1vxii1iiv1xivxvxvlixxvzujfntgg!'''',,::;~~__!+**//!!!!!\**\=!!!!!!!!!!!!!!!!!!!!!!!!!!!!\*=*\===!!!________
`-.-:'';~_!+isuTntzli/r!!__;;:::','',:'::::':,:'::,,':,:,,,:':',`..``.-......-`-..,--','!lpdp00bm0g#hc+!!!!!!!!!!!*cxz|pbeggggggg@@@gggggmhhfjTlzsxxx11i11|t|xvzz1ilzzfnzscfFkfz|gx~,:`--.-`:,,,;;_______!!=\r//=**\!!!!!!!!!!!!!+*+!!!!!!!!!/r=/r=/\+!!________
-``:,,::';__!/ir===\!!__;;;~;;;;;~;;~~~;~;___~;~~;;;~'::::'':::''',::,:',,'''`...-,,,:.-~yahd0q00gmmT!!_______!!!!xxxfIa0m#gggggggggggggggg0dFIn|zzzcci1ssscTIIkooIkEq00000#mg#nn@!:'-``..-`.```':',,';;__!!=*\+=\/r+\+r+!!!!!!!!!!!!!!!!!!!!!!!/=\r!!!!________
..:':,,::;;__!!!!!!!_____________!_!__________~;~~;;;::',''''',:'::,,,:''':'',::,',.```.'~*ewEd0d0#a/___________!!*stvIbwdaq#gggggggmmgggg00bpnut|s|zsclsTuyp0mgggggggggggggggmgas:-.`.``--.`````.`---:';;__!!\\=*=/1v*+/+/!!!!!!!!!!!__________!!!!!!!_________
-`'::~~;;;_______!!!!!!!!!______!!!___________~;;:,':':,:;;~;::':,:,',:,,''':,,''::,!!__~~~_=Ta0abb|_;;;~_______!!!ixvsepdd000000qEqqEqdbdqwaETjs|ztzzts|jyEqmggggggg@g@ggggggggm~`-..`--.`.``.....-`.`,,,~~___!!rrr\x/v1*+++r!!!!!!!!!!____~~;____________~____
::::~;___!!!!!!!!!!!!!!!!____________________~;~:',':'':~~~;~;~:,',''',:':::':':::';cj|1!__;_\Fpwao=;~;~;______!!!/xtscfIIFhEbpahhwyehheeIoyyIjfclccscsccjwkb###ggggggggggggggg00~-.`.`.-..`.-..--``....,,::~~~~___!!r/\\\\=*\=\+!!!!!!!_____~~___~~__;~;;~;____
;;;~_!!**r/!!!!!!!!________________!!!!!!!!__;;;;;::',,~;~~~;~;,','',',',:,'',:''':;Tfttir!__!vkqf1_~;~;;______!!!rvizlTjufIokapeyFFFFyIoyIeTTTsszxtls||zfukyphhqdaphq0ggggggg0qk;--`-``-.```..`..```.--.`',:::',;~__!!!///+v*+r\r+rr+=!!!____________~;;;;;____
____!!+\!!!___~_____________!!!+/r/1x\+\\/+!!__~~;~:::,~;~;;;~',:,:,,:',,''':,::',,;uFTs_=+!!\xfnxr;~~~~~~~;___!!=\xvzt|ujekwIyaawhhpIeappahFIuT|ix|tts|lcjfokohooeIekpqdqdEawIux'--``.`-`.`..`-...`..``.`...,:',,:,~~;__!!!\/ivvixxvx\\*//+!!!!!________;;~~___
___;_____~~~~;;___!!!!*r=\r/vix1iclvii*+\r!!__;;~~~:,:'':;;;:,:,',','''::::::,,:,::,con\!!__!!ix1+!;;~~~;~;~__!!!/viz|lnIu1ija0gg#00bdbwhbq0bEkut1xvttlnohEhhEaEhpEwwFIuejeEaaTs/`-.--`-.``-.--`--......-.-`-`---:':::''~;___!!*=x1ixi1ixvix*/r*!+**!!!___~;____
~;;:'~;;~~;~__!!=ii1|czs|111i1vvxi*/+!!!!__~~~;;:':,:','::::'::,'---.``-...`-''::,:,1y|_!!!/!\+*/!;;~;~;~;;___!!r/v1tltlkmg@@@@@@gq0ggg0000000yjz|v1l|Iwqdqd00mg@@@@ggmd0azvtcsix:`.`.-`.--```-..-.`..-.-`````-.-`':,,''::,~;~_!!!rri11ttzixxx\\+/x/=/!!__;~____
',,,'~~~__!!\itsnTnustx1v=+rr=!!!!!___;;~;:,:',,',:,'''':,',:,`-.`--.`.`..-`-`..---:\ux_/rxnq1!+!!;~~;;;;;~___!!!/vvsk0ggggggggggglo0ggg0m000bFjsxvttjq0qq0#g@@@@@@@gTyggoEsiv1ii;'',-`.`.--`..`..-.-`-``..`.``-.`.`...:``':,':~~__!!\riis|clcsvxxviv*r!________
.,:~~_!*===ivcczs|l11r+!!!!____~;;;~~;~,'':,:-.`..`-.-`.`::,`..-.-.`.-`-``..`-.`.``-_i!!1luIdqr!!_;~~;~~~~;_____!!+ilz1=*+vzbgg@@#gggggggq00EIuzvr\xso0gg#g@gg@@ggggmuogggqcsiccc_;,,,,::-```-.`...`..-.``-.`.``.--`.``-`---:,::':;;__!!*r\x1czlsllzv1/!!!!*!!!_
,,;_!==x1ix1++*x\/+!!__;~~;~~;~~;;;~~~,':,,:`.-..``---.-``..``--..``.-...``.`.-``--.~!__vTFyex'___;~;~;~~;____________!+**ii|njuyopqd0#000pknuv+!!=xcfpg##gggg@@@@@gggm0qd0aTlfzz_;;;;:':,,---`-`-```-- .`...``...`--``..```'`::'::::;;__!!+=rvvxctls1iix1|tztx*
;_!\=x1*/+\!!!!___;~~~;;;~;;~~;~~~;~;~',',:.```.``.`-``-..-``   .-`-...-----.--``.-`'!;!vuTs1;'__;~;;~;~~~;;_________!!!=r1vtsjjnyIhd0000Ett|x*/!_!\ilId#00mgg0qhqpEEIuTjhppeejul_~~~;~;~',,-..`..`.--`    `-.-`.`-```..-.`..`.--`.-.-':'~~;_!!!\=1xszi|fohpphuv
_!!*r+!!!___;;;~;~~~;,:::,:':''~~~~~;~':'`..``--...`-`.-``.```  ``-`-.-.-.---``-.-``-~;_!vt1!':;_;~~;;;~~~;;______~____!!\=xizTnykhhabdwot1x\*r!___!*lTy0m0000bqhayyffTjfykoIIjls_;;~~;;~~',:.`-`````--        -.`.``-```.-.--`.`.-..-.`..',,;;;_!!++ixtukEEwwTx
!!!!!___~~~;~;~~;;;;;,,':':::;~~;;~;;::.`..--`.`  `.- --.`-`.```..`..-.`-.``--.-.`.-.,_~;_/*_;~~_;;~~;;;;~;;_;;~;_______!!!\v1|tTTFFwknt***!!!!____!=tjnyd000bqqbpEwkkIyoeeyfnfzv___~_~~~;':,--````.``.-           .`-`.`-``.`.``-.-.``--`..`-`''~;__!!=i|zlul1r
!_!__~;;;~~~;~;;~;~~;;~~~;;~~;;~~;~;~,:-.``-.--... --``.`-``.-```.`.``....-`-.`.-`..-`___;;_+_~;_;~;;;;~;~~~~;;~_~;______!!r=1xlssuu|1r!!!_______~__/tjeyFhwwahEEhhyeefTuTnu|s|si_;__;~;;~:',..-..--..`-`            .--..`.`....`.`-`.```-.``.-`-.:'~;~________
!!___~~;;;~~~;~;;;~~~~;~;;~~;;;;;~;~;:,:,:--.```-`-``.--.``..``----`.```.-.-`--.`..-.`;___';!!~~_~;;;;;~___;_~~~;______!!!=*+xv1s|l1v/!!!_______;~;_!1zjjTyoFFIeoyejjuutt||lz|zl/_;___;;~;,'':.-.-`...-.-``             .```.`-``.`.``-`----````--```-':',,'',':
!!___~~;~~;;;;;~;;~~~;~~;,':':''',,':::::,',`.-.---``.`,,.,',:',.-``-.`--.`.-``..`---.'~;'::~~~'_;;;~~~_____~;;~______!!!!r\+1vx1vvr!!!!!_______~~~_!v|sfTufuuTTnfjTnltlczzf|tl|!~;;;;;~~~~,,::-.-`..-.-..`               `-..``````--.`.`..-..`-`-``-.-`.-```-`
!__~;~~;~~~;;~;~;~~,,''':::,::,:''',:,,:,:,,',,,'````---.:,',',,-.`.`---..`--....````.:,,:;_~~;'_~;~~~~;_______~;____!!!!!\\*\/ixrr=!/\!!_____~;;~;~_+1luTztffustlcztsssttt||zcc!_;~~;~~~;;,:,',-`-.--...`.--``-              .--.-...-`.--```...`.````-`-`-`.``
!_;~~:',':,:'',:::':::':,,'',,,,'':'..:..-..-`..`.-``..,'',::,',.`---`.-`.-..`.`-`````,.~bg_~~~;_~;;~;~~____________!!!!*\+/*\r+r=*\+++!!!!___;~~~;;_!\cuTl|Tjtsczttttzsssztcsc|!_;;;~~;;~~;~,',''.`----.`.`.---``.            ----..--``..-.``--..``-..``-.`...
!!!_;;;:'':,',:,'',::,,':````..`--...`----`-`---.`.---.`.-..`.``..-.--``-.--`..--`..-`.-!ggg~,'~;;;~~;;___________!!!!=++//*\/=r+*=r++r\!!_~_~~;~~;;_!r1|Tncuuzscztt|sl|l|tz|tji~~;;;~;~;;~;~~;~~,::```.-``-``.`..--.               .`-``.--`.`.``--..-`.-`-`---
!!!!!____~~~~;~~~,''::::','-..-`--`.`-`-```..```.`.-```-`.`..-`..`-``.-.---``-.`-...`-``:E@g_~;;;~;;~;_____________!!!!\+\/*\****+\+\\+rx=__;;~~~;;;_!=xxfkTj|ctllzzlltlccTlu|s+~~;~;~;;;~;;~~;~;;~:':.`.-`..`--`.-...                ``-.`..`..-...-.-`-.``-.`-
_________________~~;;~~::'':,..-.`.-```-..``.``-.-`-`-..-`-.`-.-.`..`.-.--`...`.``.`--``.`s\_!_;;~;;~~;__________!!!!!!/r+*=\*/++/+vx1itv!__;~~~~~~__**xilyekTctctllTs|u|nfzstt_;;;~;~;;;~;;~;;~;;~~:',`....--``-`..``                    .`-.-..-.-`.-```-..`-`
-,'~;~;;;~~_________~~;~;~;~;;;,',::::,':,-``````-:'':':'',''```.`-.`-----..`...-.-.':',::,~_!_~;;~;~;~__________!!!!!=***==/r+*rr1xitll__~;~;;;___!!ri1t|znfc|c|cszs|csznuslcr;;~;;~;~;~;;;~;~~~;;~~',:,-```--.`-``.-``-`...--`          ..--.``-..--....`--.-`
 -`.`-,::,:;~;~~~~~~;~;~~~;;~~;~~~~;;;~~~~;~~:,,:,:',',''',,::,:''',`....``..---:',':':,'';~;~;;;~;~~;~;_______!!!!!!!r=rr+/=r/=rxivvz|1*~;;~;__!!!r\xi1stltjjtczzssTTjj|ntt|1!_;;;;;;;;~~;~~~;;;~~~~;::::.``.-.`..`-.`...`...-.-             `.-`````-`..`.--`-
    ..-....--,'''':':;;;;;;;~~~~;~~;~;~;~;;~~~;;~~~;~;;'::,':'',''':.---`..-`.-`',:'',::,,',',',~~~~~~;;~______!!!!!!!+*+*\***r/1vx1lzs!!~~___!!=/+*\*isltxl|TtlslltzfTfunssc/_;;~;;;;~;;~~~~;;;;;~;~;:',':..``-`-``-```.-----`--`              .``-.--`..``.``-
            -`.--`.-..-``'::::;~;;~;;;~~;;;~;;~~;;;~;~,',::,,''',:,,.-.`..--.-..``,:,:',:'',':':~;~~;~;~;______!!!!!!!!!*=+*rixivi1vcix!!!!r/=iilcii1+x11v1csTjl|lcczlTjjst|v!;~;;;;~~~~;;~~;;~;~;~~~;;',,:`-`.`.---.--`-.-.``.-```-.            -.-`````.`-`--`
                 `-.`-..``--,-::':'::::'':',,':,'',''',:',,',''.-`-````..---`..`-.`-.`--..:'.!k,;~;;~;~;_______!!_!!!!!*=\/ivxiivlzvv+xi\rismggdakcts1nmgevxTyffzzzsjTufnlcz/_~~;;;;~~~~~~;~~;~;;~~;;;:,:,,-`.-..-...`.`--.-`-``-```-.               .`-`--...`.
                    `- `..`-.```-:,,':,::::,:':,:,',:,,:::::,,,..`-`-.`---`-..`-.---`..`.-`-`10::~~;~;;;_______!!!!!!!!==\=1111tzl1/!!!vEq000bdqbEkpd#m#mazTnnIkTnl|ufujfcli*_;~;;~~;;;;~;;~~~~;::',:':,.`.--````.-.----..`.`.-.``-.-.--..`           ..````--..
                        .`` `....``-.:',',,'',':':::',,::':,':..```-`.--..`.`..`````.-'-`.,:_ig,'~;;;~;;;~___!!!!_!!!!\r\i1111v|hir!!!!!=cod00mm0dd0mmgggg0yFTyknfnsnjnfnls/!;~~;~~~;~;;~~;~,''''':,.-``-`.`-..--.`.`  .`-     .-`.`-.`.`...               -...`
                                  -``.`.`-.-`:'''',,,:'''::'':-`-`-``--.-.``.-``.`'.-,'`:. :!fg~:;;~;;~~~_____!!!_!!!=\/\1xvv1xs\/!!!!!!/=xnpE000b00m##g##qyuuoFkf|Tllfu|zx*_~;~;~;;~~;;;;~,':',,..-`.-`-`-`                     ..--`-.-`--`..             --``
                                   - .-..-`----.``-.::::':,..`..-`-.`-`.`-````.-':':,':,,-.-!0@~:~~~;~~;______!!!_!!!=\==vxxivv*/+!!!!!rrvtzuyhwd000m#0000weTnjTnnfTTz|tslv!~~;~~;~;;;~;~,,',:,--``-..``..                         -```..-.....                 
                                             ```.`.-----`-```-.---..```-.---``.::',:,,:'.-'~!g@_'~~___________!!!!!!=/+r///xiv+r!!!!!!!+11vicffIpddd0000qqhkIFuyjIjc|lttlx\;;;~~;~;~;;,':',`--``..`-.-`.                           --.-`-`-.-...-`              
                                                   `--.`-`-`.`.`---``--.--.```..:''::''..`._v@@!:~____________!!!!!!++*/\=vii*/r=\r*+\xxiixxv|sTywEphwqapppyFeykofjltcczzx!~;;~;;'''::.``-.-`````.---                                 .-..`---`.`...            
                                                                --..`.`-`-`.--``-.`'`--`'',:v@@i~~____________!!!!!/\r*rvvvvir1vvs1ivixvv1xx1v\/iultfjIewahawawEknnll|cci*~~~;:::::.-..` -.                      `..``---`.-.-`-`-..-.--.     ..``.-``--        
               .-                                                           -...-`.`-.``'~~F_@@z_;____________!!!!!/*+rxvx1i1vlzjnjt|z1vi1**!!/11ttzTfFIeyeyeIkoIIncscsx*!;;~;',::...---                        `-..`-`..-..`-..--`--`-`-.     .`-`-..`-`---    
                                                                                -  ...``,_':;g@k_____!!!____!!!!!!!r=\x1i11xx|uTFenlcli=vx|eFoukIooaawwhFIuuffoFoIjlstti!_;~~:,-.`--.`                          .-``.-..``.`````-`-..---`.        `---`-..-`    
                                                                                   --,:..;n;!!@I!____!!!!!!!!!!!!!!r+\1i11iccneoomgbpdd0qbbdaEkTkIeaaoFoIkjnedafIfnlcci!~:',:`.-`---                             --.-.-...`.-`.-``...             ``.-..-`--.``-
                                                                                 - .-``::`___;ga!!__!!!!!!!!!!!!!/+r\=/i111tsTIod00gg00m0mmgggbnoyoka0g@ggggggpunjcscv/;`...`-` - ` -                                                              ``-````-```.-
                                                                                -`-.`.-.:,:!:~r#1!!_!!!!+\r!!!!!+===**=ix1ilsfewoT|sstuTict|vTh#gggggm0#m##mq0aocc|vx*;. `                                  `.. ```--```                           .-.`````.-`..
                                                                       ``        .``,,...rs',~;01!!!!!!=rr/+!!!!!/\=/r*xixzz|zc|ix=/1suyaapwFyaepEaqdb0bb0bFyIknnsvrr'                        ``````.-.`--.-.``.-`-``.`-`.                         `.-```-`..--.
                                                                       `-...`` . ---.-.;.;cz,;~cur!!!!!!=*/r=!!r*=+\rivxxxcctzlxv1i/==ixfIpwaEahEpwqqq00EIcljtztt1+!,`  .                    `-.`-`.`.`.-``---`.--.`.--`..                         .`---`-.-````
                                                                      .-~~'.-.-.``.` .`,:;c''~~~e\!!!r!!\\r==r\+=\=*vxix11vxi1xx1+/r*xvxx1csueFFyIEpayTzvx1cstzz1/!;.``.                      ```-`----.`..`-`.-`.`..`.-.                           .-``-`.`.``-
                                                                  ` -,,:~,.---.:`,,-`--rc;!r';;;ii!!//*++=+=x1i*\/*r+=ivvx1111xvi=/++i11ixzt|cujtjT||zvixvx11vx*/!!;::,..                      .   .-                                                       `.-`
                                                                 -.`+1`':`-.`-.``:_:`,''i!~\`';;~or!!\/=++\xxxii1/\r\ivvx11ixvvvx\+=11xvivst|ljjnyT||c1xi1x=ii=!!~~~_'',''--.-                                                                            -``.``
                                                              `....-',~~``...`:.;;'.'j,-__k|,:';'fc+r!=v/vxxv1vzcixiir\*//r++\\*=r+\/iv1x1tsctunjTfscii1xxvxv\/!_;':;;~':;'.`-. `.                                                                              
                                               .   `.-- ` -```'-`.``.-_;-`.--_;_`.~';~-r!:r0~''~';Ex/rr\vxxvxvccsccix1vx///+r//+===*+/vxi1xzlzl|utsssziiix1xv/!_~~~,:,!~:--.~:-..-`.                                                                            
                                                -,':;_~.-:.,'_'.--~`;-,----.-~'.`:-;=__t1_~n'::;:~nj*/\*rxizxv|sssft|xix\/=+r\r=\+\!\+*+iixx||||zzclcs|i1viv+!___;~;;',~*!:.`..;~:-`-                                                                           
                                             ...-_lx'!;zf;;v'!,../-..`..`..`~!:..,-!.r!.!#gg_:;~~~;dx/v=rv1scc|ztcsfT|cx1x*=+*!!!++r\*+=+=vv1vl|tcctczc1ii1r!____;;~~~'''!f+;:'~:_;--.                                                                          
                                      ``-```--`-`-!/F!0,o!ib_;._;.+:.~:_,,~;_!~'_!!*,`~___:u~::;;;~yEv11x1vixlsc|c|fnTnncsi/\+r=r!+/*\/\+rixxxv1x1iixsi11v=!;;~~~;;~;;~~;;;!_*__!;__,-`                                                                         
                                      ---``-..```--,_+x=;+='-;:':`!u_```~`:`- 'l'',:~'.'!=~,!';;~~;~gIciv1iv|zzzujfffjuITjzvv+/\r*/\*r/rxivvv1v1i11vxtvxv\/!;~;~;;;~;;~~~~;~;|i+!!_;_'`                                                                         
                                      `..-`.```---`..:__np:';-l.'_`~_'.`;.-',-,,'~`~:':-'y\r_-,;;~;~0gofzcslx|tzsjnunnTujFeulixi*=/*=iixx1ivvxivixxix11*\;;r+!~;;;~~~~;~~;~~'_zx1=__!!~.                                                                        
                            -`-. -.- ```--.``-`-`.`:':,';:_v:_jw|+j'..,`....``_!;~i_!_-.__vc_:,:'~~;\g0FTTtl|zlccsnfjffunuuIFft1sv1z1vcsvlzi111vv111xii0g='_=rx!_~;~;~;;;~;;;;;;c1!=v;_~-`                                         .``--  `-.``..--.`.          
                         `--`-`.`-   -````.``:''`-,'';T_d_'~!___b:Ii\,1:-. ``-._;!!_!;v1!;=r~-`'':;;~bm0peTftstnunjf|ltuuunffnnnfsctzszz|tssli1tvxvx11w@@gi;;!!+v/_;;;~;;~;;~~~;\TjfT_=i'`-                                        -```-`.---..`.-`-..`-`       
                     --`--``--.-```..```.--.'''':,~~.;~.l`.:~'!'zr_0'!,:-..,'..;_-:!;,~_x~_ki`-'':;~~\0qbpkyounfjfnuuunjzt|TujffunuunlTtnufu|l|lTssvx/rg@@gr~;!!!t1\__;~~~~~~~;:;_\=f=rF!.-.                                       `.-..`..```-```.`--`-...`-  .
                  ````.``-`-.--```---------`,;;,,``'_;_:c'__`!'!kkg'--_'~-- _,;_u~;:_!_s~;_f;`.,,,~;;;0#bqppokITTunjuTnuzsszTlcsTsujjfTjjunjszt|zxir*!!|@@@g!~;__!fi_!!_~~;,;;~:~_/ytx0jn~..          -   -.        `-    .         ..`--```-`.-.-```.`..`..----
                  `-.'',','-```-.--.``-``--.,;'``---;-;:;!,``-!`,;g'::_-~;:;;_-`;;=;_.,`_~0_x.-'::;~~;!m0qqbpwFoFFeyyTjfffncst|cssczstnTczl|cssui!v++!!!g@g@g!,;__!t!;_!/__;~',,:~iawb1rl!-`.        .---.``.`.`-   ---.-`.-          ..  ``-`.``-..-```-.`-...`
                -.---:,':`--`.-.`.-``-,;_:;~~cf:`:`-1,`~';;T:_:.'_r':'--.-..  ''.-.!_x_~'_:_*-:'::,:;,~n0qdddhwEwokFFyfufuzzszsssl|tl|c|zt|sllcyat=/!!!!E@@@@g_:~__!T!____1!;;~,:;!|sjx!!!:--`         ``-..`.`-.   ..------`              -.`-....```..``.-``-`
              ---``.`..``--..`..`''-.'#i;_ag@h_~!;,_-!F:__~~-.:!_,`-.``!~.'t;.,, `'_k,,,:,ce_-,,:,::~~~;x#0dddqbawkFkIufnjTlsz|zsz|l|ccscczszzzTj!\/\!!!t@@@@@#~;;_~!u\!_!!!1_;~~_!z==|iEf!...`-        .``-.`--   -``.--`.-`--.-`.--..--`.--`.--..`--``-.---`-.
              -,,;;,,.-.`:,~-`:`.-''!vpggnuui:_`,:;00kt;--~!'_``.-.~'!_~c!'T'`.`'!=/!!,:._rte-:,':,,;~~~~_bdqbbqqqpaFFoffjnutsstslz|ztztcszlccTThk!+=//=|g@@@@@a~;___=E/_~;sj!_!+i1pz!;~=v!~----.        ....`     -` `````..-`-`-```--``.-.`.-.`..`-..---``-.--
              .`''~'...,';_~:,/;`'1u--gI,b1;m:_em~'_mdcl=!!_~!,:;~l~/=!_~x!_+.~,`..`i!+~/~;:0`-`','',:~;___0bhhEaEapaoeFTTjnfzttstscscls|lz|ttjuyd=*=\r+y@@@@@@@l;;_~_vF!!__\\ivfl=**r/_x/ix~.`-.                       ``.-````--.-`-`-.`.``.--`-`-`------.``.`
            ``;z!::e!,:,','.-'_'_t:kn;0c:l~#a,'~!F~0,!_dmxxw_`'~_:_:;;py:,!,!j-``~,-,!t,'!y~i-..'',~;'~~;;;_dbqpwaEwEooIenfTuzslzzlc|t|c|ccslffTjFi//r\iw@@@@@g@g_,~___uz___x|++qt!\akenuou*!``-..-                      .-`---```.``.``-.-``.-.`.--..`---`-.`.`
        ...~_!:#+,_0qt!ik:`'-:_0_rd_'/d|-~0#0;ggnyg_lbj`~_lt~i_'~:1:Er;!`~:;_,`.'_~.:!_;,,;~i.`-,::'',;:~_;~_bbhhahykyeFFkkTfjt|clttct||||zccuTnF|=iiiv1#@@@@@@@@p!;~___fz__=\r0gIsd0Ey1x///|_.`````..-``-.`.`                 .`-.--`---`.``.``.`.-``.`..-..--.
        .,-F#:!:gg;vgmg!_,0!_:--.'+1;;!'-/T:-~;:;_xgg'_!~:cbT__,.``'~-;;=:1::l!...:`'m!lF!vb!`:',:::,';'~!;_;_khappeFkyIFIeFTfjjssz|zzcctztlsffTedlvxivsg@@@@@@@@@T_;;__!ji_!x|f0g0qcqpTteF!/!:--`-`-`-.-..`--.`                    -`--.`-````..-`..-.`----..``
       -`..ohqt,-!+_-|.`!rgeumk,!!:.'\x*!_|~=!~!;;_\-:\'v_;;bpw+;`;;:':.w:-!+;~c`':'r#nk`:ce_`-,,::~;,;;~!_;;~_ewkeokIkeIoyTfTfunzsz|lc|uTutuTufycxtvccq@@@@@@@g@@gr;~___!cv_vji1fmar0gm001!_!;.`---.--``---..--                      -`--`--`.-...-..----`---`.
   --`-,-.uc;'|--_!.`~-,|_;I_+e:;!.:T\`~;~;'..:-`.-r_;'':_0a!v1Ixq_.`;_'.kn'.!~~:;,1I,!\lq_0_.-`:,'':,~;~!_;_~:_ykIeookkIFoFfnjnjfffTnnnTTTufjoywzllszTg@@@@@@@@@@@f_~~___!u=!esF0zn#p1i1kI*!_!:`.-```.-`.-..`            ---                  `--`.--``..`--``-
    -_sl.`l1'-:_'`;.`.,`=*,_t`zp~!vdIt|v`.~-;'~'!;~1=,';__!_0_g_r\_c~~,',_pF\T'~,',b~x_!a+0yt~``';n,--,;~!_~:;~~!jnnyFyeyekkkjTfuunufuoyyyoyueFw1ilzzu0@@@@@@@@@@@@gz_~;___!t!vy00bmpxa0tvkx!!t_-`-.-``...`..-            --.                  ....```-..``-.--.
-`- ...,`.~-  `!_``-.`_;~~;:.!:!_,,-:_ix0l~`'__`-.`-`:|+!_d!/bn!|!=s~;-'::`.-.;ikEgq@aq#@oTd0~-.::fT:'''___;:~;;_v0cjTjjjFIIIkeTnoIFFeeFyeIeowEw\tslnpg@@@@@@@@@@@@@0!':~___!vfmgep*va|uibghal!_-..  .``.--`            ``.-..-..`.`-...           .```.`--..`-`
`:-.- .`--`` . -.-.._,-:~;!_:`_~`.~~` ;ex'.:::!:-~_!,:':'|Ee*#bij_!_;!:'*1!;g@@@@@g@@gg@@@@@g..'':=!:,:,___;;~_;__1b#EuzujjTfuTIeFIkekyyyIhwpqI||TsuEm@@@@@@@@@@@@@@@z_;;;__;!zt/jhv!uvhqi!=wjx+,.-.   -.``.        `-`..-.--.``..-...``                     `-.
:.::.``  -;'.`:_-`'-.~!!'-_:':.:;~:-`-.c~,_~'':;,!`!:-xp_!';x!\0g!T~!*_;``!.r@@@@gg@@gg@@@@@@.`','i_-,,:!_;~~~~_~;_xlEduyjfufjTkFkoIyoyFhwpEh|rjjfsub@@@@@@@@@@@@@@@@g!~~;__;_=my!!nqEegtu0t\adc_``.               `...``------...-.-`.`- .`..--              `-
_v.,;: `'_!i!r:-_!-.;!!,_:~'=:`-`:.!_,._~:1z:xx`;-,-.`!;.',/_!_gbT+1k*q;s~~~:vg@gg@gg@gg@@@@@,..:,i_.:';_;;~;~;,;;~;istfaatfTjfeoeIkIyIEpEaE\sITTfjdg@@@@@@@@@@@@@@@@@n_;~~__~_|n1_!|x*xTt1i!##hl;-.``-`           .-`.-`.`-.`-.-..-.-   ```..`.--  `- --.     `
,`-~;_,.~.~.;~~,'.*\+~,~\!_._,:`,`vj-1`';'u!j|.`-;~0_cI_`.l_;v,Toy;v!/|~~!l!z'i@I_0@g@@@gg@@@x`.,:_~.,,:b;~;_;;:;;~~_tcl|Fp0!efFoIkoEhEphhjt|yTjjuEg@@@@@@@@@@@@@@@@@@g=~;~;__;|gI!=+sqkh0sloplki~`--`.`-          ``..-``  .```.        .`.-..--`.`-`.`..`.`..-
:-`,=!l-'---_=:-:-;~.`-`.._',` `,o*:~0x-!!'_l`!!:'ru`TF-';`+;Ig:*dms_~;.F_;;'-;dw+'*@@@@@g@@@@'-.'s''',_1x!;~;~;:;~~~!zzlllkEjEnlsolIFpottewkunnne#@@@@@@@@@@@@@@@@@@@@d~~~;~__!wyq0yzfuxlcsiejbi!:`..--.          `-.`.                 ..--.`-`-...-`.``---..-
`` -`';,``;`,,',-` `'..':|#mvT!,-~`:;|,+dr1t'-.`:q~~!k_,;_!;,'b::E;`.!d*y_~er,~_nyx.+@g0@#ggg@@=`'---:;;;_z~~;_;;~;';_xt||clzjFhEp0ykkpppyoIjnTjk#@@@@@@@@@@@@@@@@@@@@@@i_;~~__~xpuTnzr|fFt=!oc0dt,`-.`-`.                                ```-.--``-``..`.-.-.``
.-. ``\;_!''.'`|u;.`:'_fq;-,;F_`1ju,!fyyg0=`dF_'!b_;~ct!;+xj,!!l!iE;,;kxeblj/`'~'ctg'gg##gdg@@@@1,,-`:~=ibI/__~~;~~;;~!g|c11ctsTjfIIFekIynffjujo0@@@@@@@@@@@@@@@@@@@@@@@0=;~~~~_!kqbnr\/T!!*Iqw1hl,-`---`.``.    `--      `                ``-`-.``-`.`-``.``...
..~:.:'t:~~k___.-;.'-'!'\``o;h~~i*i_~0__;0i!!jv;_q//01E'~:F!';ku-_g= !wnn0m_g_'r_s!m!#_l#pEagg@@@m;.'.'v`'lw__;:;~';;;;p@gF1vsllffTTTTIokuuuujkqg@@@@@@@@@@@@@@@@@@@@@@@@y_~~~;~!00c1zlegk!\|00kex'``-``-----.`-..`-.-`-.--`                     --`-...`-`-`.``
e!:''~!\x\w...;...`'._|1!.`:`:.+ngp00=gf=-1s=!+_.0b~+bn~\_:`1g|ybhh~.0yl!+g#gk;1r~_gFdgrbg0je@g@@@gw!-_\__=#___;~;;;~~',@@@@gjcctfuuujnTujnufIhg@@@@@@@@@@@@@@@@@@@@@@@@@gr;~;~~~1TEr_/wggkkuv|q0v,.`.`.`.`-`-`-`.`.-.`-.-.-`                       -.-.---..-`-
r\w:=w;_kI0~_\\_!~_:.``-~,:~`:;_!j0!_~zc00';.+_\!;_''j!+!w|migF~fu/;fyu\gg!o;gg'`,;-fg0_~gddg\gggqgg@mh~!zuz=_!~:;~,~;~~!@@@@@@g0jnjnnTTfwkTFI#@@@@@@@@@@@@@@@@@@@@@@@@@@@a_;;'~~~rr!!_~r0qf|fr!hc,-.`-`-`.--``-``.-`..-.```-                       -..````.`--.
;:.``-..`.~`,'_!-!_gF~!-n`-:~'r!`_ctggpv''gn#n!z,ek!g`yv!:g!~jgq1x0e``*wi;!e#b!i_tb=-!!g:;qg0g#gggggg@gmgtdh!!!:;~_;;;~;:#@@@@@@@@@gqkjnfnToe0@@@@@@@@@@@@@@@@@@@@@@@@@@@@g1_;,~''iE|__!!Edqf=!i+i;-`-..``--`.`--`--..``-`..```.`                      `.``.`.`-
_f:.`',!._-!j;`.` :+!p_..0':`;',,;*!_!!:t!bd;gdq;gkI0pxF!_#zigg!zs~dv_+F\|ob_g~~~!0\,_y0T!k!;mgg@g1@g@@@@yjTo__;;;~;~;~;'~@@@@@@@@@@@@@ggqpp0g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@h!_~~~:;v*f!_!|qgI*=ie1;-`.-.`-.-``.`-..-`-``..-`-`.-``--  `.--.-...-           `-.--
!''-.`~_-_!''-`~!--;.`'-j;!__,,!;~~y__~_'~,g:mI/_Tr*doxq\iog+_|mkd_:F;a!_pTxa;gq,_!_~rhg*_-s_Fjgg0uggg@@@@z/!t__;,~~~;;;;~u@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@i~~~~;:__\v_+|ggT!v0fu!:-`.-`..--`-`.`--`-`-.``.-```.``.`-`-.`.`.-.`-.            --
!*` - `!!_.-,`'!;!~j#*_` ~:f_aqd_.:,=;0-:g!v!mngg0hwpqggj;!~g_-~-!0'~:;u0|o;vg_gT:'!,qg1u0s;ttk0gdgE@m@g@g_x00~!_~~;~;~;;:~g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@d!;,;~,!|;ruqj0ggv_Ibe!-.-.``.          .`  . -      .-.`.--``-`.-````         -`.-`
'- -.`-__.-```':.,`u__.-~,t;;|:#d,_unI:+g+x~`u_0gl_~gg10_@*!+~'!dgxb!jlt1sgbhT\c!mgggg=lpo~~!_zb@#klqg@@@@u~1#__~_;~;;;;_~,x@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g*_;;;~~!!dg1tb#dT_!zn!--.                           --`----.`.-`-`..`        ```--`
. -',-~;u::--._!::,``_:`bs!`'z.f__`!f!f!F#r=0.!y#!`';+sdIw|ge1iI_/E#!guggz;0E:g_\;_=g,#00sIgg!~_0@@g@@g@@@Fs_!!___~;;;;~~;~,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0_~~;;;_\E_c1u0ggEcTi!'--`                               `.----``---`      ..`---`.
':`:;'j;!x!t0__~.~;`-~..!_-.`!u_g|s0qzEg!\0x0gl!!g0.F!kpg___!`#*~g0hsE~0s:0_@qg!I|_q@'@_dgx_!~j1~mbq#0@@@@ki!_e~;~~;__~~~'':r@@@@@@@@@@@@@@@@@@@@@@@@gg@@@@@@@@@@@@@@@@@@@@@@@l__;~~_+t!s|owggdcxzx'``-                                   `.--.``       ..-``--`
.``--v;.-!!e-`:!:,|xFu\--;!,!=e;-:,#c__iw!_!_!,!a@_gc!p!=_E,TIyugu!=_gm|_F#;!~~i~_|g:!g#0mw#gv,'~bfEggggg@qy_oh~~_~;;~;::;;~:g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@m_;~;~~!u!n!osg00Tr+/~-.`-`                                               `.--.-..
`-~,_' -. ;;`-!xqv0bt`._!:'~..-abE+,ggg1lg!,._/~,0@tbqb=E0q\g!gggm_,gxg_~__g~xz\_ggdp#wud@0tzii.xtgggg@@ggg0Ex!!;_;;~:;;;;~_'1@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@l_;;~~!pybItFgg0ITi!~..-.--                                             ..`-``.`.
--`,!kv,;-n:-`;!T0\=_;,`:_!`:;sup- `'.:;!_*v!0\f~,guwge#nsgl1z!x,./avF0=T#g@|t0_csggTEkg/gTm#_!gh,a_~T@ug0@!n/c0~;~~;;;;;~;~~~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#!;~~~_bkiw0ocIg0jl=~-`.       -...``           .-  ``                  -`-``--.-
!!:,,:uu!__:-:eu`!Ifj-_~;._!.!xh|~.:h._~,-!:-`i0|/,g#Tggug#m!gdgwu\q_hg|gTsiEnz|/amF~Tgegq!b,;!!o_eg*vg0gq@=pag_r;;~~';___~__~o@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@1__;;~I0oq*_*q0oul=_.--        `-`.            ..                      --.-`-.`-
'r` ...`:,`!!|ry__'!i#!-'~_0gg!:=uf_=r_0!00=\s/-!!g1g=_:g_!gxg@gl``~rgk0_;;x/ibgr_gFi#g_@!l0fp;#bj@0=`:kg@@gTT!00!;~~~~;_~~;,~~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g!~~~~rwmjr\1luwFv=_-`.        ...`            ..                      ..`.--.`-
kz!;;-:_~_!_~~;~;_!_r`.'r/!hqjbg+--!`:zb+va\!jtoeq;+@c=@g@b~d='gggFggb;h~a#gTvivvxxg0a00`_- +tv.a1!#gIgda0jg!mgggi_;';___~'::;~z@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@c_~';/!I1axt+dgmj\_-`.                       -.                         -..`-``
/:_;s=x./_!.-.`..~_':_!'```.a;-;1~pn;.~g*00\!!n!0_'!!#;!f!gp+~l_:d0g/gdg,tv!j!sg;0:u0o0v;'_~.,zzi!z;:ggvgE0@xb+h|Fc_:~_~''~'''~,@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@#!;,~_!tj!~F#ql*!t/'``                       .`                          --`-`-
_.!`_i'~~re,``!+.-__*'/:!l!v~'~=_:;Fyf\0+0dt0g~rhg1zgm_~0iq;=in_gim/Fuigx!!!=!F'!n:_gf_I0qEt__'yjhptgdv/\=gwTgggg!o_~_~;;_:~:~;,k@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+~;'~_/fojEqod0sx!,``            `.           -..-                        `.-.
!_;xn-:n__~'`.--..ikF\!_wlzmdg0+i;xg`:+hdF+/g_;jghgrTIggggi!1g1:T!p!T!dF0_~~_+s_;~!,#IgEc;lr`,gvFb+:ilq!!!!gg_nmE1g!;;~:~;_~;;~;;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@0_;~~!x/xhhIbgwx1/:`--    `````-.`.--...-.`--...--...-.-`.`.....``.-.``---..``
.`--'!_!_~'~,-vo!\\-xwbdgml:!fjgsf_zzEga#!0c1,!!zu@0s!g@T@p;,r'.g0gf#l0rsq0-_t=s~:~_~qic,!~,gT:_!x|vgg!1x0=t@!F_Tgi!0~~'_;';;~:~:d@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@*~;:~w1jEqm#qEic*:.`-`--``.`-`-..-`..`..-`--`..-..`.`-.-`..``-.`----`-``.`.-`
'.-`-`.:_~!`.,::,!`--Tv_'p|+b!j;:;!m0x!;-w,~t!T~;kt@g!Fg*ggb!uFs0dgg0@gp0!Fg0_:~z/\iw=0oj:wv0i_E;!!+/g0Eg00_#iygagmghl~;;:':~;~~_~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@d_;;;vTytTgggpz*~-.-``...-``-.-..```.....--```--`-.`-``..-``.-.-.`-``.`-....`
'` -.- -.''''_;~_r:.:...,x!---_j_.:,;,-#glp~epfT'+;o@x~@oaes!l_~::~k0pl@0I\gg!wgivshT11g0Flcegvnfg|_\ajqghpg0mqz0s@e;~~''':',:;~_`0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@_;~;_*TsvspIo1_:``--..--`--```-`.-.-`-```-.````-`.``..`-...-..`--...        
-`';~;'`,\!;*,:|rh0;~,~s'm0jg;!!d0g\_:;Iy|inv0*@gp_ls0!@gs*,*hbg/Tg0gamg*!,~_.|a_!g1!|b_egx+gr!1gko!ko!_;msvxIm|!g!.,n;'~':;~~;_;'_@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@u_~;;+/1Tlv0ox_.-.--`-...`.---.`.-..----.--`.```-`-.`.```-.-`-`.`-..        
.`_~:.-_.!`':.w~f!g+bg==ssd!gg*__g0t0!_1@g~__,TEgac!un\mtdng_oj!~|f_/#e#d!t+l!*~vweyi#!1pgv!giim~0~:qgpsyjp*l!hguI;aga!;u;,':;~~~;'g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g_;~~y=!_=00ei~.```..``....`.`..--`-`.```..-.-`-``.`-..-.``.---..````  ..``-
_-`~. ~F1-_~~.`_;I#ga11tyx#xbg;gd*!vcg0ug=wg+!u:mgm;e\~;g;;!;~g,,wgraIgog1`sm!/!w;:gvT1nT1zqT!gu/fyw0@@\*e!g!E!_0#w!ygl;,m!,:__;~,~!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@@I~~;rx!_1f0ga;`-`---`---..--`.`...---.```--..-`.--..-`-.---`````.-``.`..--`
` '!*__iuj._~-\.!,_im!/'m_c_kpmId0ug;*f!@kg\|IIv1a/;!IcTg0!#~fzflwg@1_#0b!~qg#E/`h~_cfngd!c/z+go00w/!iggqgg@g!!x__sod_00_pg!;_;;~;~:g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g;'~_xir/kema,`-`-.```.````-.--``-.`-.-`...-.``....``.-.---.-.`--`.`.`..`--
-~:.',`'~u!=~q!0Ioz.:~t~=_to_.vo0guhE::!_g*\oar!/*mkd0!k0y;l|00x!|rggbq0p-xggi!~t;!!!#g!!g0lkjgo0i+!_r'bg#!!/!i/!~_lkbqqfg=#_'';;~;,t@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@!:;;!!T!x1q*-.--..`...`.``.-.--`----.-`-`.-.```....``--`.``--`---.`..-`-`-
_/'!;,``;`_Evw_,-:.',.`:';:``-;-!sT_0_!',i0cT@@g@#~*m#0jlcn0yg\iv_!;d0g!yuE_y!_gm!_k*;0!cggt/+Ion_*agnx_gEgd!!/!#e:_!!!~~y0h;~''~~~:;@@@@@@@@@@@@@@@@@@@@@@@@@@@@gggggggg@@@gg@@@@@@@@e~;:v=wc\1|+:`...-``  `--``.```-`---``.-`.`....`....`.`.-`---`..--.`...--`
.`---`-:.',;:.:`:`- --~_'.'.,~!_;:,gow*0__!+cg~\qEgqlggggaIqt|~,_zky!gg#m0u_!t+zor|@;Tj@vgugp!_E@EigmxTocer1fx_|ggy1~!zxT\0ssr;~;~~:'0@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggggggggggggggggg@@g~;,_r!=/t+x,---..`---```.`-```-.--`.``.--...`.`-`.--`--``.`.--..-.....`-`
---`- .,_tvjn,.::/~,!ltguk;!'-~_r=:'ku,'gI!~c+gg@t0cgrg##@@gjg__!!j0zrrgg\__0+;y::_gg#:,+Tw~,r;0I;x0_~0@dk!Ei!T~!xTg0u!pj|g0qwc_;;~~:_@@@@@gg@@ggg@@@@@@@@@gggggggggggggggggggggggggg@@\~,;v!r!vx=`--``..---..--.`-.--....`.`.--..-.``.``.`.--`--`---``.`-..`.``
-.-`..-.`,#|ij;~\!_;,,|hgg0;;;-`--~_~,!t:~;_v_v!gsgIuk*=*@|0gqg~!r!ggfj0g;!r~v!!;;@!_m~~h:;!,*g0@v\g/g@g@go1sgk!=i@0!@E!el0~~#p_:;;~;~m@@@@@@@@gggggggggggggggggg@gggggggggggggggggggg@F~~;_;T1sf_..---`-.-`-.`-.`--`.``-.`.-----...-`--`.``.--``.`-..`--.``.-..
':~_!_~`-:y,!xm0_:z_~i;gqbggg0wghcu+;_*gEv!;;_qIgg\/bbgo_g0ggu@!~!wgggdg0EivpggT'_ml;;az__ub!!F@@\b1s:o_0gg@j0gg_g!o_#opvmg_'gg`f:~;_;_@@@@@@@@@@@@@gggggggggggg@@@@@@@@@@@@@@@g@@@ggg@g_~_+_x~=p!.`.--`.`-.-`-.    `-.--.`..--``--.----`.-.`.-.--...----`-`-.``
,_,!!;\~`.+1,'- -,~*~;Fge@kjwe0Io-_0g_~i_~z:l!gTgE=u0+c_me,g@pg_m@_!ggg0gst+_*_1;w0/-dwd*gs*,rgvg@l__o_1r#gkz0wg1_;E_xf/!i!Eg\~_!T',;:`g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@@@@@ggg@g_;~=+_/yi~`--``.-.`.```...--`-`-.`-``-``.`-`.`--..-``-.-``..`.-...`.--.`
 -;_;;;--o_!!_:..`;;'.;i0h~;~'=;!_ia-sx,z!+FtdpnqgI|ewgbTdn0gg#E_x/1gg0cnay+rlc__;_i~/!!b!-u_xggg!0tgggT|ygmsI=j1m'l''ivk;=*!!c_o/!;~~'n@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@@gggggg@@_~;!Itxjs,...````-`--.-...`-``-..`...``-.``..-`-.-...-.`-``.--`.-`.---`.
--.~;;-,oq:'txm#i~.~er:|_`.i~s=/__='+l::01zg!#rxxw!Txv@wFcns@#@j_Em!gg0@lyo,|ggn0gmvc0_gg@ggxT0_+z+1zur_!aeggv1E!_!*__:_ggu0`.~pl:b'_~,;@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@g@@gggg@@_~;_k!Ijp;-.-`..`.``..`--``-.-`--.-.```..-.``-`...`---..--.`````.-...-`-
..--.`:\xx=_=*1|_tb|..--!_!;;+c_,m'=hgI1g_vtqmd~E_hgd/_w_TIg@jlupgnpsg@@f;f@io0=czsF*gg_=bgr1r0g0ljonzjIr\\!gnc!1+*z#+qg#g#;qtI=.;_!~;;'0@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@@@@@@gg@@!~~~lb0ma_--````--.--.....``..--`---.---.--..````.`----.-`-..-.````..```
r;'~!;_..:/~,-'.-*!`'~;:l0gm:-~-'s~'vg_s+!yvf|g!_c|e!pogmdgg@gki!w+g@ggfgFygf_dvl!,'wgy!!ig#uIggdEp01os|~!~_~F#!!0g#_gg,x0gq,~iz0a!f!;~;_@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@@+~;_0giy!!`.``..-....`..``-.``-..``-..-`````--`....---.-``----``--`.-``-
  ''_`'1-'+x_.Tc__n`-,:~,0gg@00gio'_;l/azkjf1!0Tg#_1Fxmmv#g@t0g_~EEm@@@bl~!gr,i@gf_0g__g~.~w;;g!0ly!+!;_~zd=;mi_tEw|#/!;*u@g1`!.dg!!!;;;.g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggg@@+_;!l!oe+!--..``...--.-..``...```.-.`-```-`.--``.-.`-``-....-```--`.`--.
r!- ;'ad*';h!1u~vfE1;!\'#j1!_ggdEn~!+;q/syfyj*lxv#qgowzg0lggg'gExwdTggg01lg@!ay*j~:0e#f@~,vEx':g/+~0T*0E_te_v#l_x_!agvq*dhgggI|v~a!!i=~;'h@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggg@@g/_~_#c_rIo'.`-``..-`...-`.-.`--`-.-```.-.--.--.``-`-`-``..````-...-.`.`-
!feFk_z'`|f:ET'_,mgx;'-_u!,'~v\~q'!cv;!iggbI\_1!pomgugdp~!@ggyTgidqk@ge#g~cg=Te1g1l!_.'ngt;/'~~~;imkgpv*_!~~gy~Ej_!@w:hu0h0@mg_!o;F!j!;~'!@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@ggggg@@gx_;~ft+_=t~-`...``.`.`.-.-``...-.```..-.`-`.`--`..-.``.`.`.`--``--`.`.``
'=,;c_;+=_t!=y~v_:-;_;.--```. -!:;~hxtjr Tgg0l0ggtggzjrdpgq@F!swegg@@gu:g_~a_g1+d~Eg0;uuE+~g0zE1s*0wg!@o~z*ggv0jsvq_k~;aIy=fg@g!t!kp+~!;::g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@gggggggb!_~~Ik!_il!..              -`.` --`.--`.`-`-`.--`.---````--``-.-..--`.`.
.--`~*,_,-`_':`-.-;',!`'_`*v#vp'ig0l_=_f;!,Eivigb!!0!~tizgI_#p_!0cg0@gFji'fq@0\!g@@_g!_~~gg.-si+l#my0g#s/a1s!d_/=ng0;utu0gf@0g@|x:q|zra;;;p@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gg@@gggggggq\!;~pddkl*v.`                  -----.`.--``.`-``.`..``..`----.`````--``-
',.`:!_- _!-`.;*c0mcggggg@@@@@gmgg0ox\c|0F+vykp!akvgqg0rcgg!_ue@m@@fg#i0'pTgg|c!b:_!0+a+/@f!.n\;qcqi01o@!:x~!0l/;em_Igwbgge#Egg@:~bgmx!_~;~@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@g@ggggggggh=___Fpjlqj!`                   --...`````--..``-.--.-``.`-``....---.-..-
~lnju1-` `.`-_dzgq0g#@@@@@|g@Egmgv0@@0fgy/vi|h!c!bdgywgetwu_lguge@@gg_,\F#=ggojegt/!nten1ggqtpukgngFg#0yT##|yFgpgg!l!iy~Fgd@#gggl~0!1/bx~;,g@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggg@gg#gp*!_~laa1*1v-.                 --`.``.-.-.--.-.--.....``.``...---`-..`.-.
E:`~'_=:`,_~`::g=gg00dg~_sv~/j1g|cy@e|cirg!zweddm!x#Tr_0ggg!;ggaEgg@p;:g@#g@b0g!n+0+tbp!egn:!z!!qg#0!|Exr+qlggdzgFkd_obvgqgg;v0bg'Tvr*gx~_,q@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@ggggg@gggggq!_;~nw#0t+!'.                -`-`.---`--..``.-.....`----.``.`...-.```-`-
'!+!1_;`,+*v_~f_fqgggyai*_j0!vdg\~_y1tue!EggtqTg0qkqemggg#qb0ggmg@sgcg0Fgd_wgg#d~r:u,T!gwgij!Isgc1klg,#p;;t0gg~!zg~_!!@i_0mg~tgeggg/E/0!~~,s@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@gggggg@gggmmo!__;EE|\!=I'.                -`-``.`-`-`-```.--`-.`.`.`-``-``-.-...-`.``
'-'.`..:!r=\rrgn~f~.`jf;'__r,cpsc/hb!F0#g0e0aqxmgg*_eggg@gT#kjg@gc|=@=kqf!~a;ngg!++~ltgg!n0y!c!_hmI=zm_0b~\#cktgg0gxrv~|;I!gg0@gd#|~bg/0_~:/@@@gg@@@@@@@@@@@@@@@@@@@@@@@@@@ggggggg#ggg0|*!_;!ni/_\!'`              `-.-.-`.--------`-.-..-`..`.`-.-.`..`-`---.`.
!.:`,_!`,c',0np,'\_`e!\g|;:y _#bwh_ggh;g00g*n~ieg1vga0@g_!rg+!ggg@g!@\0gn,Iggd;#@~=@Iqgggn_`_;_=g@gbf/~nck0f0gggjhgggi__!#lgx#qq@@g_gs_/=;~!@@@@@ggg@@@@@@@@@@@@@@@@@@@@@@@gg@@ggggg#ggj!__~ie*_!!_:.-             ..``..--`....`--`..-`..-`---..-..---.--``--.`
\;u!'F.,!g_hf:';!!!!_. -0~bgt#;gagE\jaznpgg#0*Fr0ygo0Emmi0#l;yg0gmw_kgg0uqg_y0dgx_!dx*gj+!s0g;mg!!m#o|b!!*bsvsgy\F\v!ge~gFg00ggkgg#pg!v+s_~_@@@@@@gggggg@@@@@@@@@@@@@@@@@@@ggggg@@@ggggi____0myf/=x'``-            -.----`.---.-`.`.----`-`-----.`--``--.-....-`
'x!_k++l0i;-'.~,!kp_,vd!bg0m!*!gs~m'x1_x!Emggjx!ggbI0dgz=r!l;#ggx!cgx!;kggy*gy0T!0q!r_ggdl1bgsm!0i=ggEg!_w;hbbmm!Ig_'__ukbgFm0n0m@ge_hklk~;_@@@@@@@@@@@gggg@@@@@@@@@@@@@@@@gg@@@g@@ggg#v!___!!pt__!;-.                  `-`--`-`-         .--..`-.`````-``-`-..`
!p'0s;_n_p!v/d`..'~-'`=i#xgmgk!gEagdggp;!xqgF1#Fe!jg@@geg!_h!ogagea;fjvogFggb!m+d_@y:tn|Igggg!!gg_F;!_v_\EtEqmguzg\Tc:dggg!0ggzgmgp@s1;Tr_~_@@@@@@@@@@@gggggggg@@@@@@@@@@@@gg@@@@@@gggm\__~/b!icc0b!.`                                            -`-`--.-```.-`
x~Ir__;/j\_/!;=,.;;!_!gdy;x1tt_/j*v;ldIgI\wgny0/ggrckgI0IivmEd@@yg_|nImo@gg0*~lm1#r~#b1gw#g*+u!t1g!xaT\1+gzdgrg!gktlgg!gs~dgggF#gpgggi~+m~;_@@@@@@@@@@@@gggggggg@@@@@@@@@@@@@@@@@@@ggg0\___*o!ump!!!-.                                            `.`.--`-`-``-`
-!f,1:s0!|s!r_;,_!_`_ggb!m:!E_;~_T*yk0jz*qnvnfc~!ncIIggk@E00upom@qx~!*;d!~;!n#n_.lgsxddz*g,r_Tggg@rwpv!ggl;qxggf;c!x_ujwczh0gj!0sInn0*/xw!~!@@@@@@@@@@@@@@@g@gggggg@@@@@@@@@@@@@@@@gggEr_;~_*!bE0j0+--                                            `-..-.`--`-.-.
'r_xq/v/=\!_~~`.*ki;~!gs~r\__;_;/udza\fe#1|*!0iImqgggI!g@vqmhm@@gbp!_1mgg0uTg0_odbaggg~=#mgt_v~!/ugggsmg0o!bFg!gaggbg_g0;,gnmj100q0gg:_1!;;_@@@@@@@@@@@@@@@@@gggggggg@@@@@@@@@@@@@@gg#Iv___xfw1upbt_.-                                            --.`-``--`-```
;+~~!:/`qtvm-|/'+pap!,_jcg0gj+xTjln@d0pggetgq#ItEbg0g0x@gb#g@gmqght1!!0ggr~,:=!g0ggd:gg@gd0ggipgy!z/be!!tg\y#,r;_pg'iEcg0ggmmFndj0@ggggb0|__@@@@@@@@@@@@@@@@@@@@@ggggggg@@@@@@@@ggggggyz!__/ihi#oldi-`                                            ..`-``-----`.-
x;~!__c;Ezzl_wa_~`zt\_0!knshmvj!gniecdEgg#x~~ig0gbeg01Fjhq0gggbggx;/Ee!dn#ym@gp0't@1fg_;dqjn!eEqh#sxq0g!g0duw!~z_.!/\_;|gg#Flsggg@dyg0ptp;!_@@@@@@@@@@@@@@@@@@@@gggggggggggggggggggggmEx!_~cpaE0hfm1.-                                          .`-..--`..`-.-``
FT~1;!/rg1_vc!'.`j--.#e;!01Fg_lz~+F!oT:_Iz|mf=+Ioi|gcgIii@gb!ggg#og=jv|_~p@gbbmgllb0xg!svgb!gp0olxs#a_|;i0y_qm|0~!'tclg0\v=o!pIgmagg0h/xrtn!@@@@@@@@@@@@@@@@@@@@@@@ggggggggggggggg@ggmht!__ugw!dqgd*.-                                          `..--.`.`    `--
E|_l0lu!____q+ `vg.`-\g:!~0n|#o;pq!gst~_1ktF=1ig/_na#gog;gqzd@@g0s!;;g|_ggg!!0#k0fnxaf+;1g'F0!_/*jbz;cx+tglgd!_1.'gl!'gdg@!i!!!@dogg0Eno;rIv@@@@@@@@@@@@@@@@@@@@@@@@@ggggggggggggg@@gbjr!_;re01o0it!--`                                                         
~~~.!_fq|+t_mbjnT!dmgd_|fegxag_xyqggFt_v*cFqqx!re0yEmg_Ixgg!wgmuvga/xi!!@gg*jxFgl!_!=0;q1ku#g_r~v__y!/!pdfE!+;~:g1!*!yg#mdgv0u0#ymF@@mau~!!n@@@@@@@@@@@@@@@@@@@@@@@@@@g@ggggggggg@@@gEFc!_!p1egpo!:;.`                                                          
"""
echo
echo e- "\e[1m\ Do u know MarMu | lolcat
echo"
apt update
apt upgrade -y
apt install figlet -y
figlet Basic Installation
apt install toilet -y
apt install cowsay -y
apt install nano -y
apt install ruby -y
apt install cmatrix
gem install lolcat
figlet -f big Good Job!!! | lolcat
sleep 3
echo
cmatrix
r
u
ok
like
b
b
q
echo
echo -e "\e[1m Now Run 👉 my-banner.sh (OR) marmu.sh..!!!"
echo
echo -e "\e[1m\e[32m Modified by :\e[33m MarMu (Myanmar)"
